# Generated by Django 5.0.3 on 2024-03-29 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.TextField(max_length=10)),
                ('prenom', models.TextField(blank=True, max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('type', models.TextField(max_length=10)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phonenumber', models.TextField(blank=True, max_length=14)),
                ('privacy', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
