# Generated by Django 5.0.3 on 2024-03-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nom',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
