# Generated by Django 5.0.3 on 2024-03-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_profile_picture_enseignant_entreprise_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.TextField(choices=[('etudiant', 'etudiant'), ('enseignant', 'enseignant'), ('entreprise', 'entreprise')], null=True),
        ),
    ]
