# Generated by Django 5.0.3 on 2024-03-30 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_profile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prenom',
        ),
    ]
