# Generated by Django 5.0.3 on 2024-03-30 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_chatroom_class_publication_alter_profile_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='etablissement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='mention',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='start',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('etablissement', models.CharField(max_length=50, null=True)),
                ('mention', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
