# Generated by Django 5.0.3 on 2024-03-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
