# Generated by Django 5.0.3 on 2024-03-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_profile_adresse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='etablissement',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='mention',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='mention',
        ),
    ]
