# Generated by Django 5.0.3 on 2024-03-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_etablissement_projet_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='mention',
            field=models.TextField(choices=[('Passable', 'Passable'), ('Assez-Bien', 'Assez_bien'), ('Bien', 'Bien'), ('Trés-Bien', 'Trés-Bien')], null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
