# Generated by Django 5.0.3 on 2024-03-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_projet_month_alter_diplome_mention_alter_projet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='month',
            field=models.TextField(null=True),
        ),
    ]
