# Generated by Django 5.0.3 on 2024-03-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_projet_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='media',
            field=models.ImageField(null=True, upload_to='post_imgs/'),
        ),
    ]
