# Generated by Django 5.0.3 on 2024-03-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_publication_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_imgs/default.jpg', null=True, upload_to='profile_imgs/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
