# Generated by Django 5.0.3 on 2024-03-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_connetion_user1_remove_connetion_user2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='nom',
            field=models.TextField(null=True),
        ),
    ]
