# Generated by Django 5.0.3 on 2024-04-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_rename_date_msg_message_date_remove_chatroom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='counter',
            field=models.IntegerField(null=True),
        ),
    ]
