# Generated by Django 5.0.3 on 2024-04-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_chatroom_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='counter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
