# Generated by Django 5.0.3 on 2024-04-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_chatroom_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='CNE',
            field=models.TextField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adresse',
            field=models.TextField(blank=True, default='vide adresse', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='vide bio', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.TextField(blank=True, default='+212000000', max_length=14, null=True),
        ),
    ]
